version: "3.7"

services:
  mysql:
    image: mysql:9
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rhadamez-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - primeira-network

  api-rhada:
    build:
      context: .
    container_name: api-rhada
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - primeira-network

networks:
  primeira-network:
    name: primeiro-network
    external: true
    driver: bridge

volumes:
  db:
